---

- name: Enable PowerTools repo
  # NB: doesn't run command  `dnf config-manager --set-enabled PowerTools` as can't make that idempotent
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/Rocky-PowerTools.repo 
    create: false # raises error if not already installed
    regexp: enabled=
    line: enabled=1

- name: Enable EPEL
  ansible.builtin.dnf:
    name: epel-release

- name: Create Slurm user
  ansible.builtin.user:
    name: slurm
    system: yes
    shell: /sbin/nologin

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ control_packages if inventory_hostname in query('vars', 'slurm_control_hosts') else compute_packages }}"
  vars:
    control_packages:
      - slurm-slurmctld
    compute_packages:
      - slurm-slurmd
