---

- include_tasks: pre.yml

- name: Ensure OpenHPC repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
  loop: "{{ ohpc_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Include variables for OpenHPC version
  include_vars:
    file: "ohpc-{{ openhpc_version }}"

- name: Find PowerTools repo
  find:
    paths: /etc/yum.repos.d
    patterns: '*-*PowerTools.repo'
  register: powertools
  when: ansible_distribution_major_version == "8"

- name: Enable PowerTools repo
  # NB: doesn't run command  `dnf config-manager --set-enabled PowerTools` as can't make that idempotent
  lineinfile:
    path: "{{ powertools.files[0].path }}" # 8.2: /etc/yum.repos.d/CentOS-PowerTools.repo 8.3: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    create: false # raises error if not already installed
    regexp: enabled=
    line: enabled=1
  when: ansible_distribution_major_version == "8"

- name: Build host-specific list of required slurm packages
  set_fact:
    openhpc_slurm_pkglist: "{{ openhpc_slurm_pkglist | default([]) + item.value }}"
  loop: "{{ ohpc_slurm_packages | dict2items }}"
  when: (openhpc_enable.get(item.key, false)) or ()

- name: Install required slurm packages
  yum:
    name: "{{ openhpc_slurm_pkglist | reject('eq', '') }}"
  when: openhpc_slurm_pkglist | default(false, true)

- name: Install packages from openhpc_packages variable
  yum:
    name: "{{ openhpc_packages }}"

...
