---

- name: Install packages
  block:
    - include_tasks: install.yml
  tags: install

- name: Configure
  block:
    - include: configure.yml
  tags: configure

- include: post-configure.yml
  when:
    - openhpc_enable.runtime | default(false) | bool
    # Requires operational slurm cluster
    - openhpc_slurm_service_started | bool
  tags: post-configure

...
