- name: Enable batch on configless login-only nodes
  set_fact:
    openhpc_enable: "{{ openhpc_enable | combine({'batch': true}) }}"
  when:
    - openhpc_slurm_configless
    - openhpc_login_only_nodes in group_names

- name: Select slurm service to control
  set_fact:
    openhpc_slurm_service: "{{ ohpc_slurm_services[item] }}"
  loop: "{{ ohpc_slurm_services.keys() | list }}"
  when: "openhpc_enable.get(item, false)"
  tags: always
