---
# NOTE: We need this running before slurmdbd
- name: Restart Munge service
  service:
    name: munge
    state: restarted
  when: slurm_service_enabled | bool

- name: Stop slurmds
  service:
    name: slurmd
    state: stopped
  when: inventory_hostname not in query('vars', 'slurm_control_hosts')
  listen: Restart Slurm daemons

- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    daemon_reload: "{{ slurmctld_dropins.changed | default('no') }}"
  when: inventory_hostname in query('vars', 'slurm_control_hosts')
  listen: Restart Slurm daemons

- name: Check slurmctld up
  wait_for:
    port: 6817
    delay: 2
  run_once: true
  listen: Restart Slurm daemons
  

- name: Start slurmds
  service:
    name: slurmd
    state: started
  when: inventory_hostname not in query('vars', 'slurm_control_hosts')
  listen: Restart Slurm daemons
